import Head from "next/head";

function Header() {
  /**
   * Change meta
   * Not sure if the css link is being used.
   */
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link href="/styles/globals.css" rel="stylesheet"></link>
    </Head>
  );
}

export default Header;
